// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ad_log.proto

package com.nx.stream.entity;

public interface ProcessInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.ProcessInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool join_server_log = 1;</code>
   */
  boolean getJoinServerLog();

  /**
   * <code>optional int64 process_timestamp = 2;</code>
   */
  long getProcessTimestamp();

  /**
   * <code>optional int64 retry_count = 3;</code>
   */
  long getRetryCount();
}
